import React from 'react'
import '../../css/T_and_C.css'

const TERMS_CONDITIONS_PAGE = () => {
   window.scrollTo(0, 0)

   return (
      <main className="t-and-c-container">
         <h1>Terms and Conditions</h1>

         <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor, voluptatem laudantium quae reprehenderit cumque sapiente quo provident autem aperiam minima temporibus quod possimus expedita eligendi voluptas repellendus. Et, dignissimos neque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde consectetur fugit modi laboriosam voluptatibus consequatur, non quod ullam sed veniam, accusamus odit esse nemo nisi doloremque vitae labore totam accusantium! <br/></p>

         <h2>Lorem ipsum dolor</h2>

         <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor, voluptatem laudantium quae reprehenderit cumque sapiente quo provident autem aperiam minima temporibus quod possimus expedita eligendi voluptas repellendus. Et, dignissimos neque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde consectetur fugit modi laboriosam voluptatibus consequatur, non quod ullam sed veniam, accusamus odit esse nemo nisi doloremque vitae labore totam accusantium! Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor, voluptatem laudantium quae reprehenderit cumque sapiente quo provident autem aperiam minima temporibus quod possimus expedita eligendi voluptas repellendus. Et, dignissimos neque? Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde consectetur fugit modi laboriosam voluptatibus consequatur, non quod ullam sed veniam, accusamus odit esse nemo nisi doloremque vitae labore totam accusantium! <br/></p>

         <h2>Dolor sit amet conq</h2>

         <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione at velit aut laboriosam totam alias nisi. Eum numquam, nam molestias ipsum quod provident praesentium rem accusamus necessitatibus dignissimos ea quasi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, quo distinctio. Eos tenetur, asperiores quos voluptatem iste adipisci! Dolore nihil sit natus ea laborum explicabo libero unde dolorum quae reiciendis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt quo dolorum perferendis praesentium ratione assumenda rerum minus quos et. Praesentium asperiores a aliquid! Et reiciendis autem beatae nihil soluta reprehenderit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione at velit aut laboriosam totam alias nisi. Eum numquam, nam molestias ipsum quod provident praesentium rem accusamus necessitatibus dignissimos ea quasi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, quo distinctio. Eos tenetur, asperiores quos voluptatem iste adipisci! Dolore nihil sit natus ea laborum explicabo libero unde dolorum quae reiciendis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt quo dolorum perferendis praesentium ratione assumenda rerum minus quos et. Praesentium asperiores a aliquid! Et reiciendis autem beatae nihil soluta reprehenderit. Lorem ipsum dolor sit amet consectetur adipisicing elit. <br /> <br />Ratione at velit aut laboriosam totam alias nisi. Eum numquam, nam molestias ipsum quod provident praesentium rem accusamus necessitatibus dignissimos ea quasi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, quo distinctio. Eos tenetur, asperiores quos voluptatem iste adipisci! Dolore nihil sit natus ea laborum explicabo libero unde dolorum quae reiciendis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt quo dolorum perferendis praesentium ratione assumenda rerum minus quos et. Praesentium asperiores a aliquid! Et reiciendis autem beatae nihil soluta reprehenderit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione at velit aut laboriosam totam alias nisi. Eum numquam, nam molestias ipsum quod provident praesentium rem accusamus necessitatibus dignissimos ea quasi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, quo distinctio. Eos tenetur, asperiores quos voluptatem iste adipisci! Dolore nihil sit natus ea laborum explicabo libero unde dolorum quae reiciendis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt quo dolorum perferendis praesentium ratione assumenda rerum minus quos et. Praesentium asperiores a aliquid! Et reiciendis autem beatae nihil soluta reprehenderit.</p>

         <h2>Accusamus ea quasi</h2>

         <p>Eos tenetur, asperiores quos voluptatem iste adipisci! Dolore nihil sit natus ea laborum explicabo libero unde dolorum quae reiciendis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt quo dolorum perferendis praesentium ratione assumenda rerum minus quos et. Praesentium asperiores a aliquid! Et reiciendis autem beatae nihil soluta reprehenderit. Lorem ipsum dolor sit amet consectetur adipisicing elit. <br /> <br />Ratione at velit aut laboriosam totam alias nisi. Eum numquam, nam molestias ipsum quod provident praesentium rem accusamus necessitatibus dignissimos ea quasi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, quo distinctio. Eos tenetur, asperiores quos voluptatem iste adipisci! Dolore nihil sit natus ea laborum explicabo libero unde dolorum quae reiciendis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt quo dolorum perferendis praesentium ratione assumenda rerum minus quos et. Praesentium asperiores a aliquid! Et reiciendis autem beatae nihil soluta reprehenderit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione at velit aut laboriosam totam alias nisi. Eum numquam, nam molestias ipsum quod provident praesentium rem accusamus necessitatibus dignissimos ea quasi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus, quo distinctio. Eos tenetur, asperiores quos voluptatem iste adipisci! Dolore nihil sit natus ea laborum explicabo libero unde dolorum quae reiciendis? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nesciunt quo dolorum perferendis praesentium ratione assumenda rerum minus quos et. Praesentium asperiores a aliquid! Et reiciendis autem beatae nihil soluta reprehenderit.</p>
      </main>
   )
}

export default TERMS_CONDITIONS_PAGE